apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abyss
  labels:
    app: abyss
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abyss
  labels:
    app: abyss
subjects:
- kind: ServiceAccount
  name: abyss
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: abyss
  apiGroup: rbac.authorization.k8s.io