apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abyss
  name: abyss
spec: 
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector: 
    matchLabels: 
      app: abyss
  template: 
    metadata: 
      labels: 
        app: abyss
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec: 
      containers: 
      - image: {{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}
        name: abyss
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $val := .Values.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: abyss
              key: {{ $key }}
        {{- end }}
        {{- range $key, $val := .Values.env.normal }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 80
            path: /healthz
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 4
          failureThreshold: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 80
            path: /healthz
          initialDelaySeconds: 4
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2