replicaCount: 1
image:
  repository: ghcr.io/mattjeanes/abyss/abyss.web:latest
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "100m"
env:
  secret:
    SecretExample: "test"
  normal:
    Example: "test"
