name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skipBuild:
        description: 'Skip Build (deploy only)'
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Build Docker images
      run: |
        for appname in Abyss.Web; do
          app=`echo $appname | tr '[:upper:]' '[:lower:]'`
          echo "Building $appname docker"
          docker build -t $app -f "$appname/Dockerfile" .
        done
      if: github.event.inputs.skipBuild != 'true'
        
    - name: Push Docker images
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io --username MattJeanes --password-stdin
        for appname in Abyss.Web; do
          app=`echo $appname | tr '[:upper:]' '[:lower:]'`
          echo "Deploying $appname"
          docker tag $app ghcr.io/mattjeanes/abyss/$app:latest
          docker push ghcr.io/mattjeanes/abyss/$app:latest
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main' && github.event.inputs.skipBuild != 'true'
  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout Infrastructure repo
      uses: actions/checkout@v2.4.2
      with:
        repository: MattJeanes/Abyss-Infrastructure
        path: infrastructure
    
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Kubernetes
      uses: Azure/aks-set-context@v2.1
      with:
        resource-group: abyss
        cluster-name: abyss
        
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: charts/abyss/values.yaml
      env:
        ingress.host: "${{ secrets.HOST }}"
      
        env.secret.Authentication__Discord__ClientSecret: "${{ secrets.DISCORD_CLIENTSECRET }}"
        env.secret.Authentication__Google__ClientSecret: "${{ secrets.GOOGLE_CLIENTSECRET }}"
        env.secret.Authentication__Steam__ApplicationKey: "${{ secrets.STEAM_APPLICATIONKEY }}"
        env.secret.Azure__ClientSecret: "${{ secrets.AZURE_CLIENTSECRET }}"
        env.secret.Cloudflare__ApiKey: "${{ secrets.CLOUDFLARE_APIKEY }}"
        env.secret.ConnectionStrings__Abyss: "${{ secrets.DATABASECONNECTIONSTRING }}"
        env.secret.Discord__Token: "${{ secrets.DISCORD_TOKEN }}"
        env.secret.GMod__ApiKey: "${{ secrets.GMOD_APIKEY }}"
        env.secret.Jwt__Key: "${{ secrets.JWT_KEY }}"
        env.secret.Pushover__ApiKey: "${{ secrets.PUSHOVER_APIKEY }}"
        env.secret.Pushover__UserKey: "${{ secrets.PUSHOVER_USERKEY }}"
        env.secret.Tumblr__ConsumerKey: "${{ secrets.TUMBLR_CONSUMERKEY }}"
        env.secret.Tumblr__ConsumerSecret: "${{ secrets.TUMBLR_CONSUMERSECRET }}"
        env.secret.Tumblr__Token: "${{ secrets.TUMBLR_TOKEN }}"
        env.secret.Tumblr__TokenSecret: "${{ secrets.TUMBLR_TOKENSECRET }}"

        env.normal.Authentication__Discord__ClientId: "${{ secrets.DISCORD_CLIENTID }}"
        env.normal.Authentication__Google__ClientId: "${{ secrets.GOOGLE_CLIENTID }}"
        env.normal.Azure__ClientId: "${{ secrets.AZURE_CLIENTID }}"
        env.normal.Azure__SubscriptionId: "${{ secrets.AZURE_SUBSCRIPTIONID }}"
        env.normal.Azure__TenantId: "${{ secrets.AZURE_TENANTID }}"
        env.normal.Cloudflare__Email: "${{ secrets.CLOUDFLARE_EMAIL }}"
        env.normal.Cloudflare__Zone: "${{ secrets.CLOUDFLARE_ZONE }}"
        env.normal.GMod__BaseUrl: "${{ secrets.GMOD_BASEURL }}"
        env.normal.QuoteOfTheDay__DiscordChannelId: "${{ secrets.QUOTEOFTHEDAY_DISCORDCHANNELID }}"
        env.normal.Reminder__DiscordChannelId: "${{ secrets.REMINDER_DISCORDCHANNELID }}"
        env.normal.TeamSpeak__Host: "${{ secrets.TEAMSPEAK_HOST }}"
        env.normal.Tumblr__BlogName: "${{ secrets.TUMBLR_BLOGNAME }}"
        env.normal.GPTClient__BaseUrl: "${{ secrets.GPTCLIENT_BASEURL }}"
        
    - name: Install Abyss
      run: |
        helm upgrade --install --wait --atomic --debug \
          abyss ./abyss \
          --namespace default
      working-directory: charts
        
    - name: Wait for certificate to be ready
      run: |
        . "./Common/Helpers.ps1"
        Wait-KubeCertificate -CertificateName "abyss-tls"
      shell: pwsh
      working-directory: infrastructure/scripts
